ayoubfaouzi/al-khaser

README.md
al-khaser/Al-khaser.cpp
al-khaser/Anti Debug/HardwareBreakpoints.cpp
al-khaser/Anti Debug/SoftwareBreakpoints.cpp
al-khaser/Anti Debug/SoftwareBreakpoints.h
al-khaser/Shared/Common.cpp
al-khaser/Shared/Main.h
al-khaser/Shared/Utils.cpp
al-khaser/al-khaser.vcxproj
al-khaser/al-khaser.vcxproj.filters

#include <Windows.h>
#include <stdio.h>
void Myfunction_Trap_Debugger()
{
/* Setting INT 3 BP here would be detected */
int a=1;
int b=2;
int c=a+b;
printf ("I am the function that i'll trap your debugger, %d", c);
}
void Myfunction_Adresss_Next()
{ 
};
BOOL SoftwareBreakpoints(void* pMemory,  size_t SizeToCheck)
{
/* Software breakpoints aka INT 3 represented in the IA-32 instruction set with the opcode CC (0xCC). 
Given a memory addresse and size, it is relatively simple to scan for the byte 0xCC -> if(pTmp[i] == 0xCC)
An obfuscated method would be to check if our memory byte xored with 0x55 is equal 0x99 for example ... */
unsigned char *pTmp = (unsigned char*)pMemory;
unsigned char tmpchar = 0;  
for (size_t i = 0; i < SizeToCheck; i++)
{
tmpchar = pTmp[i];
if( 0x99 == (tmpchar ^ …

add Software Breakpoints detection

---

al-khaser/Al-khaser.cpp
al-khaser/Anti Debug/NtQuerySystemInformation_SystemKernelDebuggerInformation.cpp
al-khaser/Anti Debug/NtQuerySystemInformation_SystemKernelDebuggerInformation.h
al-khaser/Anti Debug/SharedUserData_KernelDebugger.cpp
al-khaser/Anti Debug/SharedUserData_KernelDebugger.h
al-khaser/Shared/Main.h
al-khaser/al-khaser.vcxproj
al-khaser/al-khaser.vcxproj.filters

Hi, thanks for this great project! I've already found and fixed one bug in [ScyllaHide](https://github.com/x64dbg/ScyllaHide) thanks to it.
I noticed the anti-debug detection is very complete on the user mode side, but there is no detection of kernel debuggers. This can be interesting if you are running e.g. malware in a VM with a kernel debugger attached.
This PR adds two checks that essentially check the same thing (from the kernel's perspective), as explained in the comments. However they do this in different ways, the second of which is not very well known/widely used as far as I know, but is actually much harder to hide for the debugger.

Add two kernel debugger checks

---

README.md
al-khaser/Al-khaser.cpp
al-khaser/Anti Debug/ProcessJob.cpp
al-khaser/Anti Debug/ProcessJob.h
al-khaser/Shared/Main.h
al-khaser/al-khaser.vcxproj
al-khaser/al-khaser.vcxproj.filters

Debugging applications commonly place debugees into a job object for various reasons, e.g. so that the child processes are closed if the parent crashes. We can exploit this to identify cases where the al-khaser process is part of a job, excluding some edge cases (e.g. console hosting). This new check identifies if the current process is part of a job and, if so, enumerates the job objects to see if any of them are outside a whitelist.
You can test this check by running the al-khaser process from within Visual Studio via Debug -> Start Without Debugging.

Added process job anti-debug check.

---

README.md
al-khaser/Al-khaser.cpp
al-khaser/Anti VM/Services.cpp
al-khaser/Anti VM/Services.h
al-khaser/Shared/Main.h
al-khaser/al-khaser.vcxproj
al-khaser/al-khaser.vcxproj.filters
al-khaser/timing-attacks/timing.cpp

Driver services are a good indicator of VMs. So far I've got driver names in for VMware and VirtualBox.

VM driver service checks

---

al-khaser/timing-attacks/timing.cpp

Previously had no check to see if the DLL / API lookups succeeded, causing null ref if they did.
These calls can fail in sandboxes where the calls are filtered.

Fix null references in timing.cpp

---

README.md
al-khaser/Al-khaser.cpp
al-khaser/Anti Debug/WriteWatch.cpp
al-khaser/Anti Debug/WriteWatch.h
al-khaser/Shared/Main.h
al-khaser/al-khaser.vcxproj
al-khaser/al-khaser.vcxproj.filters

Using VirtualAlloc's MEM_WRITE_WATCH and associated APIs to look for hooks and debuggers.
Writeup here:
https://codeinsecurity.wordpress.com/2018/01/24/anti-debug-with-virtualallocs-write-watch/

Memory write watch anti-debug

---

al-khaser/Al-khaser.cpp
al-khaser/Anti Debug/WriteWatch.cpp
al-khaser/Anti Debug/WriteWatch.h

New test cases with multiple APIs.
This might need some testing across Windows versions to avoid false positives, but I suspect it won't be a problem as we're relying only on reference parameters not being written to when invalid parameters are passed to APIs, which is unlikely to change across versions.

Vastly improved VirtualAlloc write watch tests

---

al-khaser/Anti VM/Qemu.cpp
al-khaser/Anti VM/VMWare.cpp
al-khaser/Anti VM/VirtualBox.cpp
al-khaser/Shared/Utils.cpp
al-khaser/Shared/Utils.h

Call GetProcAddress to obtain pointers to EnumSystemFirmwareTables and GetSystemFirmwareTable since they aren't available on XP.

XP Support

---

al-khaser/Anti VM/Generic.cpp

Previously we were only checking PhysicalDrive0 with the size IOCTL check, but on some systems PhysicalDrive0 might be associated with a single disk in a software RAID volume or an appliance boot volume. Such cases would be incorrectly flagged as a VM for being under 80GB in size. This new code instead finds the OS drive letter, maps that to a set of physical disks, then sums the sizes.  If anything goes wrong it falls back to the old method of just checking PhysicalDrive0.
This resolves #118.

Improved disk size IOCTL checks

---

al-khaser/Al-khaser.cpp
al-khaser/Anti Debug/TLS_callbacks.cpp
al-khaser/Anti Debug/TLS_callbacks.h

Re-wrote TLS callbacks as a check rather than message box to avoid forcing user interaction. This means that organisations can use al-khaser in CI and other automated testing for builds (e.g. for sandbox products) more easily.

TLS callback improvements

---

al-khaser/Al-khaser.cpp
al-khaser/Shared/Common.cpp
al-khaser/Shared/Common.h
al-khaser/timing-attacks/timing.cpp
al-khaser/timing-attacks/timing.h

This overhauls how we do the timing attack stuff, so we can use exec_check on those functions and return a sensible status based on whether APIs returned expected values. In the process I noticed the locky timer trick had the return values backwards so I fixed that too.
See #114 for more info (I'll close it when this PR is resolved)

Overhaul of timing attack code + fix the locky timer trick

---

al-khaser/AntiAnalysis/process.cpp
al-khaser/AntiDebug/HardwareBreakpoints.cpp
al-khaser/AntiDebug/MemoryBreakpoints_PageGuard.cpp
al-khaser/AntiDebug/ModuleBoundsHookCheck.cpp
al-khaser/AntiDebug/PageExceptionBreakpointCheck.cpp
al-khaser/AntiDebug/ProcessJob.cpp
al-khaser/AntiDebug/ScanForModules.cpp
al-khaser/AntiDebug/WriteWatch.cpp
al-khaser/AntiVM/Generic.cpp
al-khaser/AntiVM/Qemu.cpp
al-khaser/AntiVM/Services.cpp
al-khaser/AntiVM/VMWare.cpp
al-khaser/AntiVM/VirtualBox.cpp
al-khaser/CodeInjection/CreateRemoteThread.cpp
al-khaser/CodeInjection/NtCreateThreadEx.cpp
al-khaser/CodeInjection/QueueUserAPC.cpp
al-khaser/CodeInjection/RtlCreateUserThread.cpp
al-khaser/CodeInjection/SetWindowsHooksEx.cpp
al-khaser/Shared/Common.cpp
al-khaser/Shared/Utils.cpp
al-khaser/Shared/log.cpp
al-khaser/TimingAttacks/timing.cpp

Fix for HardwareBreakpoints routine
Update process.cpp
Fix multiple bugs in WMI related routines
Fix memory leak in check_mac_addr routine
Update MemoryBreakpoints_PageGuard.cpp
Fix multiple bugs in ScanForModules.cpp
Fix bug in IsBadLibrary
Fix number of bugs in get_system_firmware
Fix InitWMI routine
Update IsBadLibrary 
Remove incorrect result checks and wrong printf specifiers in ScanForModules.cpp
Fix null pointer dereference in qemu_firmware_ACPI routine
Fix null pointer dereferences in VirtualBox.cpp & VMWare.cpp
Fix QueueUserAPC_Injection routine by rewrite
Fix null pointer dereference in setupdi_diskdrive routine
Add error handling in log_print
Fix null pointer dereference in print_last_error routine, add more error handling
Fixes in Services.cpp
Fix signed/unsigned mismatch for …

Bug fixes 5

---

al-khaser/AntiVM/Generic.cpp

Replaced `StrStrI` check with a `wcscmp`. Fixes #151.

Fixed false positive in VirtualBox BIOS serial number WMI check

---

al-khaser/AntiDebug/ScanForModules.cpp
al-khaser/Shared/APIs.cpp
al-khaser/Shared/APIs.h
al-khaser/Shared/ApiTypeDefs.h
al-khaser/Shared/Utils.cpp
al-khaser/Shared/Utils.h
al-khaser/Shared/WinStructs.h

Due to incorrect PEB64 address: on both systems distance between addresses of native and wow64 PEB's is one page ( 0x1000 ), but the order is different.

Crash fix for 32 bit app running on Win7 x64

---

al-khaser/AntiDump/SizeOfImage.cpp

`SizeOfImage()` is supposed to increase the reported size of the EXE in the loader module list. However it was writing the new size value to the `DllBase` field instead of `SizeOfImage`.
Additionally, the function was using `InMemoryOrderModuleList` to find the EXE, but due to this list being in memory order as the name implies, it usually actually modified the wrong module. I changed this to use `InLoadOrderModuleList` instead, in which the EXE is always the first entry.
While this code works, it does contain some ugly pointer hackery which is needed because `winternl.h` is woefully inadequate and doesn't define the needed fields. I added comments for clarification of the fields, but if this is not enough I suggest replacing `winternl.h` with a header(s) containing the uncensored types …

Anti-dump: fix SizeOfImage() modifying the wrong module and field

---

al-khaser/AntiVM/VirtualBox.cpp

The check to see if a property is a `VT_BSTR` should be done with AND, not OR.
I found this because my compiler complained about these lines with:
`warning C4554: '|': check operator precedence for possible error; use parentheses to clarify precedence`. So I added parentheses to silence the warning as well.

Fix VARIANT vartype flags check on WMI properties

---

al-khaser/AntiDebug/NtQueryInformationProcess_ProcessDebugObject.cpp
al-khaser/AntiDebug/NtQueryInformationProcess_ProcessDebugObject.h

This PR makes two changes to the DebugObjectHandle check:
- The return status must now be `STATUS_PORT_NOT_SET`. Any other status is a failure. This addresses #195.
- A second call to `NtQueryInformationProcess` has been added with the debug object handle and return length buffers overlapping. The idea is that this will catch anti-anti-debuggers making use of logic similar to the following:
```
// ...call original NtQueryInformationProcess here...
*(HANDLE*)ProcessInformation = NULL;
return STATUS_PORT_NOT_SET;
```
The check will now catch this because the combined handle/return length is incorrectly set to `NULL` in the above example, overwriting the real return length. The reason `sizeof(HANDLE)` is the correct value of the overlapping buffer is because the kernel writes the return …

DebugObjectHandle improvements

---

README.md
al-khaser/Al-khaser.cpp
al-khaser/AntiVM/Generic.cpp
al-khaser/AntiVM/Generic.h

This implements all the checks from #189.  Let me know what you think - I'm happy to implement any suggested changes.
I'm participating in Hacktoberfest 2020, and figured this would be a good issue to tackle for that.  If you are OK with this PR would you mind adding a label to it called `hacktoberfest-accepted` so it will be counted? Thank you!
https://hacktoberfest.digitalocean.com/details#details

Fix #189 - Add known hostname / username checks from malware

---

al-khaser/AntiDebug/NtSetInformationThread_ThreadHideFromDebugger.cpp

Previously we were using BOOL for the hidden thread flag, but that's typedef int which is 4 bytes. This query call expects a 1-byte bool instead, so the NtQueryInformationThread call would always fail with a length mismatch. Due to the logic in the function, this resulted in silently returning no detection.
One important detail of note is that because bool is a single byte local variable, it is free to be allocated anywhere and isn't necessarily aligned. This commit introduces an AlignedBool struct that uses the alignas keyword to get around this issue.
Three new checks are added in this commit:
The first check detects if a length mismatch status is returned for legitimate calls, which might happen if someone writes a buggy hook that incorrectly assumes a BOOL is passed rather than a …

Bug fixes and new checks in ThreadHideFromDebugger.

---

al-khaser/AntiDebug/ParentProcess.cpp
al-khaser/pch.h

The previous method of checking if the process was launched by Explorer was very prone to false positives, since it would return a detection if you have Explorer process isolation enabled (i.e. one process per explorer window).
The new method finds the parent process ID and checks the main module path to see if it's an explorer.exe process. The full path is checked so as to avoid the trick of just renaming the parent process to explorer.exe somewhere else in the filesystem.
If the parent process filename or explorer path cannot be fetched for some reason, the check falls back to the old method. It also handles the situation where GetExplorerPIDbyShellWindow fails and returns zero.
@LordNoteworthy: Requesting review from you just to sanity-check my code and see if I missed anything.

Improve parent process check to avoid false positives.

---

al-khaser/Al-khaser.cpp
al-khaser/AntiDebug/ScanForModules.cpp
al-khaser/AntiDebug/ScanForModules.h

The memory walk check was broken because it assumed that memory regions would be executable. It also started at the wrong address - AllocationBase is the start of the allocator region, whereas BaseAddress is the actual start of the region. This has now been fixed.
This commit also adds a new check, which scans for memory structures that the .NET runtime creates to track loaded modules. This should catch injected modules even if they're dynamically loaded from memory.
This fixes #234 and #237.

Fix ScanForModules_MemoryWalk_Hidden and add new .NET structure scan.

---

README.md
al-khaser/Al-khaser.cpp
al-khaser/AntiAnalysis/process.cpp
al-khaser/TimingAttacks/timing.cpp
al-khaser/TimingAttacks/timing.h

Added WaitForMultipleObjects to timing checks, Frida processes and updated readme

Added WaitForMultipleObjects and Frida processes

---

README.md
al-khaser/Al-khaser.cpp
al-khaser/AntiVM/Generic.cpp
al-khaser/AntiVM/Generic.h

Hello. By the number of SMBIOS tables you can detect VM. For example, Virtual box and Qemu have only 10 SMBIOS tables. On a real table machine there will be at least 100 SMBIOS tables.

Checking the virtual machine through the number of SMBIOS tables

---

al-khaser/AntiVM/Generic.cpp

If a flash drive smaller than 80 GB is mounted, there will be a false positive.

Working with a mounted flash drive

---

al-khaser/AntiVM/Generic.cpp

+Fix incorrect comparison. Table counting may have completed early due to an incorrect comparison. 
+refacto.

Fix incorrect comparison when counting smbios tables

---

.github/workflows/release.yml
README.md
appveyor.yml

This PR serves to address some of the issues with accessing the compiled binaries for this project. By generating releases for this project and attaching binaries to them, it should work around workflow artifacts expiring and any issues with binaries in the repo itself.
Included changes:
- bump the version of the upload-artifact version to a supported one
- change the existing build action to only run on PR events. This includes PRs being opened, additional commits being added to the source branch, etc
- add a new workflow that supports a release workflow
This would require that after merges to master, a maintainer go generate a release for the project, and associated git tag. That will trigger this new workflow and upload the built binaries (unzipped) to the release.
I've tested this on …

Attach project binaries to releases for accessibility

---

al-khaser/AntiDebug/NtSystemDebugControl.cpp

Fixed #254 
If NtSystemDebugControl returns STATUS_NOT_IMPLEMENTED, it can't be flagged as debugging.

Fix NtSystemDebugControl STATUS_NOT_IMPLEMENTED cases

---

README.md
al-khaser/Al-khaser.cpp
al-khaser/AntiVM/Generic.cpp
al-khaser/AntiVM/Generic.h

Windows ACPI Emulated devices Table is a special table provided by hypervisors for improving Windows guest stability.
Spec:  https://download.microsoft.com/download/7/E/7/7E7662CF-CBEA-470B-A97E-CE7CE0D98DC2/WAET.docx
Both QEMU and Virtualbox build WAET table in their sources, and probably VMWare too

Add check for WAET ACPI table presence

---

README.md
al-khaser/Al-khaser.cpp
al-khaser/AntiVM/Generic.cpp
al-khaser/AntiVM/Generic.h
al-khaser/AntiVM/KVM.cpp
al-khaser/AntiVM/Parallels.cpp
al-khaser/AntiVM/Parallels.h
al-khaser/AntiVM/Qemu.cpp
al-khaser/AntiVM/Qemu.h
al-khaser/AntiVM/VMWare.cpp
al-khaser/AntiVM/VirtualBox.cpp
al-khaser/AntiVM/VirtualPC.cpp
al-khaser/AntiVM/Xen.cpp
al-khaser/AntiVM/Xen.h
al-khaser/Shared/Utils.cpp

Looking Glass (https://looking-glass.io/) - Looking Glass is an open source application that allows the use of a KVM (Kernel-based Virtual Machine) configured for VGA PCI Pass-through without an attached physical monitor, keyboard or mouse.
Used in Hypervisor-Phantom (https://github.com/Scrut1ny/Hypervisor-Phantom)
VirtualDisplayDriver (VDDSysTray.exe) is used in conjunction with looking glass (there is also older IddSampleDriver which we must check by kanging GPU VM strings from VMAware - recently added method by me)
I also added glob handling for registry checker and added PCI scan (VEN_1AF4* and so on) method (adaptation of my patches from VMAware)
TODO (can be done in other PRs):
1. Kang(?) GPU capabilities & Driver friendly names checks from vmaware
2. Kang(?) other reg checks from …

Looking Glass, VirtualDisplayDriver & PCI VID scan VM detection methods

---

README.md
al-khaser/Al-khaser.cpp
al-khaser/AntiVM/Generic.cpp
al-khaser/AntiVM/Generic.h
al-khaser/AntiVM/Qemu.cpp

This PR adds advanced ACPI checks for generic sandboxes & QEMU
After a small research I discovered that QEMU sets PM=0 (1 = desktop, 2 = mobile) so we need to account ACPI battery
For generic sandboxie detection I introduced checks agains PNP devices that are present on all PCs

Implement advanced ACPI scan for generic sandbox & QEMU

---

al-khaser/AntiDebug/ScanForModules.cpp
al-khaser/AntiVM/Generic.cpp
al-khaser/Shared/Utils.cpp
al-khaser/TimingAttacks/timing.cpp

DONE: 
- fix build warning 
- apply code style for modified src-files
This MR fixes the following noisy warnings:
```
AntiDebug\ScanForModules.cpp(416,8): warning C4101: 'moduleName': unreferenced local variable
AntiVM\Generic.cpp(2005,11): warning C4200: nonstandard extension used: zero-sized array in struct/union
Shared\Utils.cpp(1146,33): warning C4267: '=': conversion from 'size_t' to 'USHORT', possible loss of data
TimingAttacks\timing.cpp(121,9): warning C4101: 'hThread': unreferenced local variable
TimingAttacks\timing.cpp(123,20): warning C4101: 'dwThreadID': unreferenced local variable
```

 fix build warnings and apply code style
